chore(formatting): Print Line Position in to Header (#90)
Output the location along with the file name when printing the header.

At first, I thought it was unnecessary because the code lines are
printed together with line numbers at the bottom, but it turned out to
be harder to recognize than expected.

**Before**

```plain
error: simplify-slice-range
  --> slice0.gno
```

**After**

```plain
error: simplify-slice-range
  --> slice0.gno:10:6
```